### ISSUE TITLE
Open to a large Pull request? Or should I fork?

### ISSUE THREAD

**Issue by wormeyman** [hirofumii/vscode-theme-rubyblue#1]
I'm the creator of https://github.com/Brackets-Themes/RubyBlue which is one of the many derivatives of the original ruby blue theme, I'm working right now locally to get the colors in line with the brackets edition and I'm wondering if this is still maintained and what your thoughts are about working together to get it like the brackets colors or if you prefer this theme the way it is and I should fork?

**Comment by hiz8** [comment]
I also used Brackets-Themes/RubyBlue before, so I'd like to bring it closer to it.
Therefore, pull requests are greatly appreciated!

**Comment by wormeyman** [comment]
Great 👍 I'll get started

**Comment by wormeyman** [comment]
Working on it here: https://github.com/wormeyman/vscode-theme-rubyblue/tree/bracketsstyle
